### ISSUE TITLE
胡桃工具箱安裝失敗

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao.Deployment#14]
繼先前  (https://github.com/DGP-Studio/Snap.Hutao/issues/1975)  測試版發生0x80040154後 正式版也復現了
msix包正確下載 但安裝失敗

Snap Hutao Deployment Tool [1.16.3]
PackagePath: C:\Users\A\Desktop\Snap.Hutao.msix
FamilyName:
------------------------------------------------------------
?法找到所需?? [GlobalSign Code Signing Root R45]，正在? GlobalSign 下?
Required Certificate [GlobalSign Code Signing Root R45] not found, downloading from GlobalSign
正在向 本地?算机/受信任的根????机构 添加??
如果你?法理解?窗中的文本，??? [是]

Adding certificate to LocalMachine/ThirdParty Root CA store,
please click [yes] on the [Security Waring] dialog

?于更多安全信息，?查看下方的网址
For more security information, please visit the url down below
https://support.globalsign.com/ca-certificates/root-certificates/globalsign-root-certificates
初始化 PackageManager...
Initializing PackageManager...
Exception occured:
System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): 類別未登錄 (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32)
   at WinRT.BaseActivationFactory..ctor(String, String)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Windows.Management.Deployment.AddPackageOptions..ctor()
   at Snap.Hutao.Deployment.Invocation.RunDeploymentCoreAsync(String, String , Boolean) in J:\Projects\Snap.Hutao.Deployment\src\Snap.Hutao.Deployment\Invocation.cs:line 79
   at Snap.Hutao.Deployment.Invocation.RunDeploymentAsync(InvocationContext context) in J:\Projects\Snap.Hutao.Deployment\src\Snap.Hutao.Deployment\Invocation.cs:line 57
按下回??退出...
Press enter to exit...

**Comment by SSB-ARFCN** [comment]
使用管理員執行powershell可正常安裝
